### PR TITLE
Update encode_util.rb

### PR DESCRIPTION
**Pull request by reese-li**
Get rid of "can't modify frozen string" error.

### CODE REVIEW

**Comment by jlee-r7** [comment]
In what scenario does this manifest?  Nothing I can find in this codebase `freeze`s any strings.

**Comment by mwrock** [comment]
I'd bet its coming from a frozen string passed to `Client.new'. Either the username, password or one of the options that gets passed to `oem_or_unicode_str` and then forwarded to `encode_utf16le` from there. This would happen if user got set from `ENV['USERNAME']` or domain was set from `ENV['USERDOMAIN']`.

```
irb(main):006:0> a=ENV['USERNAME']
=> "mwrock"
irb(main):007:0> a=a.force_encoding('utf-8')
RuntimeError: can't modify frozen String
        from (irb):7:in `force_encoding'
        from (irb):7
        from C:/opscode/chefdk/embedded/bin/irb:11:in `<main>'
```

**Comment by mwrock** [comment]
I'm :+1: on this

**Comment by mwrock** [comment]
I totally forgot about this PR when submitting #30 last night. That one closes an additional possible hole. Also ir just deletes the first line of the encode method. Anyone see any potential problem deleting that line?

**Comment by zenchild** [comment]
I think we can safely delete it.

**Comment by zenchild** [comment]
@mwrock  Do you want to just remove that line in your PR and we can just close this PR?

**Comment by mwrock** [comment]
That sounds good. Closing in favor of #30 but thanks much @reese-li!

**Pull request closed without merging**
