### PR TITLE
Avoid usage of legacy algorithms on libssl-3.0+

### LINKED ISSUE #49: Ciphers unsupported by default provider in OpenSSL 3
In OpenSSL 3, some considered weak ciphers and digests were moved to the legacy provider. Because it is not loaded by default, rubyntlm does not work.

```
  1) Net::NTLM::Client::Session#sign_message signs a message and when KEY_EXCHANGE is true
     Failure/Error: rc4 = OpenSSL::Cipher.new("rc4")
     
     OpenSSL::Cipher::CipherError:
       unsupported
     # ./lib/net/ntlm/client/session.rb:128:in `initialize'

....
  6) Net::NTLM::Message::Type2 should generate a type 3 response
     Failure/Error: OpenSSL::Digest::MD4.digest pwd
     
     OpenSSL::Digest::DigestError:
       Digest initialization failed: initialization error
     # ./lib/net/ntlm.rb:149:in `ntlm_hash'
```

The user needs either to enable the provider via the configuration (very inconvenient), or access the ciphers in the legacy provider programmatically, see: https://github.com/ruby/openssl/issues/500#issuecomment-1100660910.

The new Debian and new Ubuntu versions (amongst which 22.04 LTS) ship OpenSSL 3.

### PR DESCRIPTION
**Pull request by larskanis**
Single DES and MD4 are considered legacy algorithms in OpenSSL/libssl-3.0. They can be enabled by adjusting the openssl configuration file or by using the new provider concept of OpenSSL-3. Editing the configuration must be done by each user of rubyntlm, which is very inconvenient. The provider API is not yet supported by the ruby binding to OpenSSL.

So it's better to avoid the legacy algorithms at all.

The single DES algorithm can easily implemented by a two key 3-DES run.
The md4 implementation is taken from here:
  https://gist.github.com/tprynn/5419da1a2ad8935c1fff
And the rc4 implementation is taken from here and modified:
  https://github.com/caiges/Ruby-RC4/blob/082fce56ab707dc77442709357cf176f7b3b6f22/lib/rc4.rb

Fixes #49

### CODE REVIEW

**Comment by larskanis** [comment]
A CI run on Ubuntu-22.04 without this patch fails like so: https://github.com/larskanis/rubyntlm/runs/7068752401?check_suite_focus=true
With this patch all is green: https://github.com/larskanis/rubyntlm/actions/runs/2567751689

**Comment by larskanis** [comment]
@mwrock Gentle ping... Any chance to get this into a new release?

**Comment by larskanis** [comment]
Background is that I maintain https://github.com/larskanis/pg-ldap-sync/ which can use NTLM authentication through the `rubyntlm` gem. And `pg-ldap-sync` is used by people with no Ruby knowledge at all, so they just use `apt install ruby` and `gem install` and run the command. It is therefore not suitable to make use of a Gemfile and bunder for them to overcome compatibility issues with modern OpenSSL.

**Comment by donoghuc** [comment]
Thanks for this patch. Do you know if there is a way to force the client to always use NTLM v2 (which I think would at least stop using the MD4 algorithm?) I looked a bit but I dont see anything obvious.

**Comment by larskanis** [comment]
@donoghuc Sorry no, I don't know much about the NTLM internals.

**Comment by donoghuc** [comment]
Thanks I will let you know what solution we (over at puppet https://github.com/puppetlabs/bolt/pull/3191 ) come up with. Cheers.

**Comment by eglitobias** [comment]
We also have exactly the same issue. It would be very nice if we can find a solution here soon.

**Comment by igoshevski** [comment]
+1

**Comment by pcai** [comment]
thank you!

**Pull request merged**
