### PR TITLE
Update Negotiate Flags

### PR DESCRIPTION
**Pull request by n00tmeg**
This PR updates the Negotiate Flags to match the Microsoft documentation (https://msdn.microsoft.com/en-us/library/cc236650.aspx).

Obs.: MBx (Must Be Zero) flags and other unreferenced flags were removed. Please let me know if you think they should be there, I will put them back.

### CODE REVIEW

**Review by mwrock — DISMISSED** [review]
This is probably totally fine, but there is the possibility this could break someone using the removed keys. Might not be a bad idea to keep those at the bottom of the list and commented as undocumented. They may be documented somewhere else since I doubt they were originally added arbitrarily.

**Comment by n00tmeg** [comment]
So, I found out I never pushed the changes for this. I'm sorry for the delay (almost 4 years!). I made the requested changes.

**Comment by pcai** [comment]
thanks for your contribution @n00tmeg. is this still helpful to merge? I tried spot checking that it matches the documentation but since they're not in the same order it was a bit hard to validate.

**Review by pcai — APPROVED** [review]
thanks, i went through the docs and everything looks as expected

**Pull request merged**
